data/sodapoppin/2025-01/2341488283_suprise_w/_chat_-_(sodapoppin)_-_january_1,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2341488283_suprise_w_chat_-_sodapoppin_-_january_1_2025.mp4
  rendered_at: '2025-12-08 00:02:58'
  title: Suprise w/ Chat - (sodapoppin) - January 1, 2025
data/sodapoppin/2025-01/2343182092_cooking_w/_chat_-_(sodapoppin)_-_january_3,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2343182092_cooking_w_chat_-_sodapoppin_-_january_3_2025.mp4
  rendered_at: '2025-12-08 02:45:43'
  title: Cooking w/ Chat - (sodapoppin) - January 3, 2025
data/sodapoppin/2025-01/2343182092_vei_does_chance's_makeup_w/_chat_-_(sodapoppin)_-_january_3,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2343182092_vei_does_chances_makeup_w_chat_-_sodapoppin_-_january_3_2025.mp4
  rendered_at: '2025-12-08 02:38:07'
  title: Vei Does Chance's Makeup w/ Chat - (sodapoppin) - January 3, 2025
data/sodapoppin/2025-01/2344199105_dog_tricks_w/_chat_-_(sodapoppin)_-_january_4,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2344199105_dog_tricks_w_chat_-_sodapoppin_-_january_4_2025.mp4
  rendered_at: '2025-12-08 02:53:46'
  title: Dog Tricks w/ Chat - (sodapoppin) - January 4, 2025
data/sodapoppin/2025-01/2345138072_costume_w/_chat_-_(sodapoppin)_-_january_5,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2345138072_costume_w_chat_-_sodapoppin_-_january_5_2025.mp4
  rendered_at: '2025-12-08 03:12:08'
  title: Costume w/ Chat - (sodapoppin) - January 5, 2025
data/sodapoppin/2025-01/2345138072_punishment_w/_chat_-_(sodapoppin)_-_january_5,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2345138072_punishment_w_chat_-_sodapoppin_-_january_5_2025.mp4
  rendered_at: '2025-12-08 04:38:17'
  title: Punishment w/ Chat - (sodapoppin) - January 5, 2025
data/sodapoppin/2025-01/2347758992_tyler1_league_coaching_session_w/_chat_-_(sodapoppin)_-_january_8,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2347758992_tyler1_league_coaching_session_w_chat_-_sodapoppin_-_january_8_2025.mp4
  rendered_at: '2025-12-08 05:25:06'
  title: Tyler1 League Coaching Session w/ Chat - (sodapoppin) - January 8, 2025
data/sodapoppin/2025-01/2349429275_everhood_w/_chat_reacting_to_chat_-_(sodapoppin)_-_january_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2349429275_everhood_w_chat_reacting_to_chat_-_sodapoppin_-_january_10_2025.mp4
  rendered_at: '2025-12-08 08:18:44'
  title: Everhood w/ Chat Reacting to Chat - (sodapoppin) - January 10, 2025
data/sodapoppin/2025-01/2349429275_song_burning_desires_w/_chat_-_(sodapoppin)_-_january_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2349429275_song_burning_desires_w_chat_-_sodapoppin_-_january_10_2025.mp4
  rendered_at: '2025-12-08 05:35:28'
  title: Song Burning Desires w/ Chat - (sodapoppin) - January 10, 2025
data/sodapoppin/2025-01/2349429275_song_fireflies_w/_chat_-_(sodapoppin)_-_january_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2349429275_song_fireflies_w_chat_-_sodapoppin_-_january_10_2025.mp4
  rendered_at: '2025-12-08 05:40:20'
  title: Song Fireflies w/ Chat - (sodapoppin) - January 10, 2025
data/sodapoppin/2025-01/2349429275_song_let_it_go_w/_chat_-_(sodapoppin)_-_january_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2349429275_song_let_it_go_w_chat_-_sodapoppin_-_january_10_2025.mp4
  rendered_at: '2025-12-08 05:29:20'
  title: Song Let It Go w/ Chat - (sodapoppin) - January 10, 2025
data/sodapoppin/2025-01/2349429275_song_lost_boy_w/_chat_-_(sodapoppin)_-_january_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2349429275_song_lost_boy_w_chat_-_sodapoppin_-_january_10_2025.mp4
  rendered_at: '2025-12-08 05:33:41'
  title: Song Lost Boy w/ Chat - (sodapoppin) - January 10, 2025
data/sodapoppin/2025-01/2353239513_t1_vs_sodapoppin_duel_planning_w/_chat_-_(sodapoppin)_-_january_14,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2353239513_t1_vs_sodapoppin_duel_planning_w_chat_-_sodapoppin_-_january_14_2025.mp4
  rendered_at: '2025-12-08 08:51:41'
  title: T1 vs Sodapoppin Duel Planning w/ Chat - (sodapoppin) - January 14, 2025
data/sodapoppin/2025-01/2354081887_t1_vs_sodapoppin_duel_w/_chat_-_(sodapoppin)_-_january_15,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2354081887_t1_vs_sodapoppin_duel_w_chat_-_sodapoppin_-_january_15_2025.mp4
  rendered_at: '2025-12-08 11:35:38'
  title: T1 vs Sodapoppin Duel w/ Chat - (sodapoppin) - January 15, 2025
data/sodapoppin/2025-01/2355950535_casting_tyler1's_warcraft_iii_event_w/_chat_-_(sodapoppin)_-_january_17,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2355950535_casting_tyler1s_warcraft_iii_event_w_chat_-_sodapoppin_-_january_17_2025.mp4
  rendered_at: '2025-12-08 13:51:41'
  title: Casting Tyler1's Warcraft III Event w/ Chat - (sodapoppin) - January 17,
    2025
data/sodapoppin/2025-01/2357816822_nelson_w/_chat_-_(sodapoppin)_-_january_19,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2357816822_nelson_w_chat_-_sodapoppin_-_january_19_2025.mp4
  rendered_at: '2025-12-08 13:59:20'
  title: Nelson w/ Chat - (sodapoppin) - January 19, 2025
data/sodapoppin/2025-01/2358748593_alexbones_interview_w/_chat_-_(sodapoppin)_-_january_20,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2358748593_alexbones_interview_w_chat_-_sodapoppin_-_january_20_2025.mp4
  rendered_at: '2025-12-08 14:15:31'
  title: Alexbones Interview w/ Chat - (sodapoppin) - January 20, 2025
data/sodapoppin/2025-01/2358748593_nelson_w/_chat_-_(sodapoppin)_-_january_20,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2358748593_nelson_w_chat_-_sodapoppin_-_january_20_2025.mp4
  rendered_at: '2025-12-08 14:21:54'
  title: Nelson w/ Chat - (sodapoppin) - January 20, 2025
data/sodapoppin/2025-01/2360544855_hide_and_seek_w/_chat_-_(sodapoppin)_-_january_22,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2360544855_hide_and_seek_w_chat_-_sodapoppin_-_january_22_2025.mp4
  rendered_at: '2025-12-08 17:32:15'
  title: Hide and Seek w/ Chat - (sodapoppin) - January 22, 2025
data/sodapoppin/2025-01/2361397145_nelson_w/_chat_-_(sodapoppin)_-_january_23,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2361397145_nelson_w_chat_-_sodapoppin_-_january_23_2025.mp4
  rendered_at: '2025-12-08 17:40:16'
  title: Nelson w/ Chat - (sodapoppin) - January 23, 2025
data/sodapoppin/2025-01/2362517320_onlyfangs_irl_guild_meeting_w/_chat_-_(sodapoppin)_-_january_24,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2362517320_onlyfangs_irl_guild_meeting_w_chat_-_sodapoppin_-_january_24_2025.mp4
  rendered_at: '2025-12-08 19:18:53'
  title: OnlyFangs IRL Guild Meeting w/ Chat - (sodapoppin) - January 24, 2025
data/sodapoppin/2025-01/2363327420_nelson_w/_chat_-_(sodapoppin)_-_january_25,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2363327420_nelson_w_chat_-_sodapoppin_-_january_25_2025.mp4
  rendered_at: '2025-12-08 19:27:38'
  title: Nelson w/ Chat - (sodapoppin) - January 25, 2025
data/sodapoppin/2025-01/2364353892_nelson_w/_chat_-_(sodapoppin)_-_january_26,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2364353892_nelson_w_chat_-_sodapoppin_-_january_26_2025.mp4
  rendered_at: '2025-12-08 22:45:24'
  title: Nelson w/ Chat - (sodapoppin) - January 26, 2025
data/sodapoppin/2025-01/2364353892_warcraft_iii_custom_maps_w/_chat_-_(sodapoppin)_-_january_26,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2364353892_warcraft_iii_custom_maps_w_chat_-_sodapoppin_-_january_26_2025.mp4
  rendered_at: '2025-12-08 22:36:43'
  title: Warcraft III Custom Maps w/ Chat - (sodapoppin) - January 26, 2025
data/sodapoppin/2025-01/2365214813_nelson_w/_chat_-_(sodapoppin)_-_january_27,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2365214813_nelson_w_chat_-_sodapoppin_-_january_27_2025.mp4
  rendered_at: '2025-12-08 22:48:26'
  title: Nelson w/ Chat - (sodapoppin) - January 27, 2025
data/sodapoppin/2025-01/2366950968_nelson_w/_chat_-_(sodapoppin)_-_january_29,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2366950968_nelson_w_chat_-_sodapoppin_-_january_29_2025.mp4
  rendered_at: '2025-12-08 22:55:06'
  title: Nelson w/ Chat - (sodapoppin) - January 29, 2025
data/sodapoppin/2025-01/2367853227_nelson_w/_chat_-_(sodapoppin)_-_january_30,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2367853227_nelson_w_chat_-_sodapoppin_-_january_30_2025.mp4
  rendered_at: '2025-12-08 23:00:58'
  title: Nelson w/ Chat - (sodapoppin) - January 30, 2025
data/sodapoppin/2025-02/2369520525_onlyfangs_molten_core_raid_w/_chat_-_(sodapoppin)_-_february_1,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2369520525_onlyfangs_molten_core_raid_w_chat_-_sodapoppin_-_february_1_2025.mp4
  rendered_at: '2025-12-09 13:55:28'
  title: OnlyFangs Molten Core Raid w/ Chat - (sodapoppin) - February 1, 2025
data/sodapoppin/2025-02/2374066827_kingdom_come:_deliverance_ii_#ad_w/_chat_-_(sodapoppin)_-_february_6,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2374066827_kingdom_come_deliverance_ii_ad_w_chat_-_sodapoppin_-_february_6_2025.mp4
  rendered_at: '2025-12-09 15:01:10'
  title: 'Kingdom Come: Deliverance II #ad w/ Chat - (sodapoppin) - February 6, 2025'
data/sodapoppin/2025-02/2374953042_onlyfangs_molten_core_raid_(reaction)_w/_chat_-_(sodapoppin)_-_february_7,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2374953042_onlyfangs_molten_core_raid_reaction_w_chat_-_sodapoppin_-_february_7_2025.mp4
  rendered_at: '2025-12-09 18:14:57'
  title: OnlyFangs Molten Core Raid (Reaction) w/ Chat - (sodapoppin) - February 7,
    2025
data/sodapoppin/2025-02/2374953042_onlyfangs_molten_core_raid_(reaction)_w/_chat_-_(sodapoppin)_-_february_7,_2025_muted:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2374953042_onlyfangs_molten_core_raid_reaction_w_chat_-_sodapoppin_-_february_7_2025_muted.mp4
  rendered_at: '2025-12-13 15:33:10'
  title: OnlyFangs Molten Core Raid (Reaction) w/ Chat - (sodapoppin) - February 7,
    2025
data/sodapoppin/2025-02/2375792144_onlyfangs_molten_core_raid_w/_chat_-_(sodapoppin)_-_february_8,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2375792144_onlyfangs_molten_core_raid_w_chat_-_sodapoppin_-_february_8_2025.mp4
  rendered_at: '2025-12-09 21:46:12'
  title: OnlyFangs Molten Core Raid w/ Chat - (sodapoppin) - February 8, 2025
data/sodapoppin/2025-02/2377573386_onlyfangs_molten_core_raid_(reaction)_w/_chat_-_(sodapoppin)_-_february_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2377573386_onlyfangs_molten_core_raid_reaction_w_chat_-_sodapoppin_-_february_10_2025.mp4
  rendered_at: '2025-12-10 01:03:06'
  title: OnlyFangs Molten Core Raid (Reaction) w/ Chat - (sodapoppin) - February 10,
    2025
data/sodapoppin/2025-02/2379488038_onlyfangs_molten_core_raid_w/_chat_-_(sodapoppin)_-_february_12,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2379488038_onlyfangs_molten_core_raid_w_chat_-_sodapoppin_-_february_12_2025.mp4
  rendered_at: '2025-12-10 03:48:03'
  title: OnlyFangs Molten Core Raid w/ Chat - (sodapoppin) - February 12, 2025
data/sodapoppin/2025-02/2387433399_onlyfangs_molten_core_raid_(reaction)_w/_chat_-_(sodapoppin)_-_february_21,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2387433399_onlyfangs_molten_core_raid_reaction_w_chat_-_sodapoppin_-_february_21_2025.mp4
  rendered_at: '2025-12-10 04:59:13'
  title: OnlyFangs Molten Core Raid (Reaction) w/ Chat - (sodapoppin) - February 21,
    2025
data/sodapoppin/2025-02/2388277253_onlyfangs_molten_core_raid_(20)_w/_chat_-_(sodapoppin)_-_february_22,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2388277253_onlyfangs_molten_core_raid_20_w_chat_-_sodapoppin_-_february_22_2025.mp4
  rendered_at: '2025-12-10 07:24:02'
  title: OnlyFangs Molten Core Raid (20) w/ Chat - (sodapoppin) - February 22, 2025
data/sodapoppin/2025-02/2391777300_warcraft_iii_w/_chat_-_(sodapoppin)_-_february_26,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2391777300_warcraft_iii_w_chat_-_sodapoppin_-_february_26_2025.mp4
  rendered_at: '2025-12-10 09:21:53'
  title: Warcraft III w/ Chat - (sodapoppin) - February 26, 2025
data/sodapoppin/2025-03/2395380915_warcraft_iii_w/_chat_-_(sodapoppin)_-_march_2,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-03/2395380915_warcraft_iii_w_chat_-_sodapoppin_-_march_2_2025.mp4
  rendered_at: '2025-12-13 20:01:38'
  title: Warcraft III w/ Chat - (sodapoppin) - March 2, 2025
data/sodapoppin/2025-03/2396145543_molten_core_w/_chat_-_(sodapoppin)_-_march_3,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-03/2396145543_molten_core_w_chat_-_sodapoppin_-_march_3_2025.mp4
  rendered_at: '2025-12-13 22:04:42'
  title: Molten Core w/ Chat - (sodapoppin) - March 3, 2025
data/sodapoppin/2025-03/2396145543_warcraft_iii_w/_chat_-_(sodapoppin)_-_march_3,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-03/2396145543_warcraft_iii_w_chat_-_sodapoppin_-_march_3_2025.mp4
  rendered_at: '2025-12-13 23:11:01'
  title: Warcraft III w/ Chat - (sodapoppin) - March 3, 2025
