data/sodapoppin/2025-01/2341488283_suprise_w/_chat_-_(sodapoppin)_-_january_1,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2341488283_suprise_w_chat_-_sodapoppin_-_january_1_2025.mp4
  link: https://www.youtube.com/watch?v=gA7giNKnG1Y
  title: Suprise w/ Chat - (sodapoppin) - January 1, 2025
  uploaded_at: '2025-12-09 23:30:54'
data/sodapoppin/2025-01/2343182092_cooking_w/_chat_-_(sodapoppin)_-_january_3,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2343182092_cooking_w_chat_-_sodapoppin_-_january_3_2025.mp4
  link: https://www.youtube.com/watch?v=cP234qtDn0c
  title: Cooking w/ Chat - (sodapoppin) - January 3, 2025
  uploaded_at: '2025-12-09 23:32:41'
data/sodapoppin/2025-01/2343182092_vei_does_chance's_makeup_w/_chat_-_(sodapoppin)_-_january_3,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2343182092_vei_does_chances_makeup_w_chat_-_sodapoppin_-_january_3_2025.mp4
  link: https://www.youtube.com/watch?v=J4wI4UQX1MU
  title: Vei Does Chance's Makeup w/ Chat - (sodapoppin) - January 3, 2025
  uploaded_at: '2025-12-09 23:32:35'
data/sodapoppin/2025-01/2344199105_dog_tricks_w/_chat_-_(sodapoppin)_-_january_4,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2344199105_dog_tricks_w_chat_-_sodapoppin_-_january_4_2025.mp4
  link: https://www.youtube.com/watch?v=atk6V7ZbLmE
  title: Dog Tricks w/ Chat - (sodapoppin) - January 4, 2025
  uploaded_at: '2025-12-09 23:32:49'
data/sodapoppin/2025-01/2345138072_costume_w/_chat_-_(sodapoppin)_-_january_5,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2345138072_costume_w_chat_-_sodapoppin_-_january_5_2025.mp4
  link: https://www.youtube.com/watch?v=6yq6bJnXPfg
  title: Costume w/ Chat - (sodapoppin) - January 5, 2025
  uploaded_at: '2025-12-09 23:33:01'
data/sodapoppin/2025-01/2345138072_punishment_w/_chat_-_(sodapoppin)_-_january_5,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2345138072_punishment_w_chat_-_sodapoppin_-_january_5_2025.mp4
  link: https://www.youtube.com/watch?v=rTH0V0sjDHw
  title: Punishment w/ Chat - (sodapoppin) - January 5, 2025
  uploaded_at: '2025-12-09 23:34:10'
data/sodapoppin/2025-01/2347758992_tyler1_league_coaching_session_w/_chat_-_(sodapoppin)_-_january_8,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2347758992_tyler1_league_coaching_session_w_chat_-_sodapoppin_-_january_8_2025.mp4
  link: https://www.youtube.com/watch?v=4wdF81mN1I4
  title: Tyler1 League Coaching Session w/ Chat - (sodapoppin) - January 8, 2025
  uploaded_at: '2025-12-09 23:34:37'
data/sodapoppin/2025-01/2349429275_everhood_w/_chat_reacting_to_chat_-_(sodapoppin)_-_january_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2349429275_everhood_w_chat_reacting_to_chat_-_sodapoppin_-_january_10_2025.mp4
  link: https://www.youtube.com/watch?v=sQBXUoczK_0
  title: Everhood w/ Chat Reacting to Chat - (sodapoppin) - January 10, 2025
  uploaded_at: '2025-12-09 23:36:26'
data/sodapoppin/2025-01/2349429275_song_burning_desires_w/_chat_-_(sodapoppin)_-_january_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2349429275_song_burning_desires_w_chat_-_sodapoppin_-_january_10_2025.mp4
  link: https://www.youtube.com/watch?v=XHcrdWSNkzU
  title: Song Burning Desires w/ Chat - (sodapoppin) - January 10, 2025
  uploaded_at: '2025-12-09 23:34:49'
data/sodapoppin/2025-01/2349429275_song_fireflies_w/_chat_-_(sodapoppin)_-_january_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2349429275_song_fireflies_w_chat_-_sodapoppin_-_january_10_2025.mp4
  link: https://www.youtube.com/watch?v=AwjnL6kAGJc
  title: Song Fireflies w/ Chat - (sodapoppin) - January 10, 2025
  uploaded_at: '2025-12-09 23:34:55'
data/sodapoppin/2025-01/2349429275_song_let_it_go_w/_chat_-_(sodapoppin)_-_january_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2349429275_song_let_it_go_w_chat_-_sodapoppin_-_january_10_2025.mp4
  link: https://www.youtube.com/watch?v=8LTuUXawnPA
  title: Song Let It Go w/ Chat - (sodapoppin) - January 10, 2025
  uploaded_at: '2025-12-09 23:34:41'
data/sodapoppin/2025-01/2349429275_song_lost_boy_w/_chat_-_(sodapoppin)_-_january_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2349429275_song_lost_boy_w_chat_-_sodapoppin_-_january_10_2025.mp4
  link: https://www.youtube.com/watch?v=9Ug81npKHrQ
  title: Song Lost Boy w/ Chat - (sodapoppin) - January 10, 2025
  uploaded_at: '2025-12-09 23:34:47'
data/sodapoppin/2025-01/2353239513_t1_vs_sodapoppin_duel_planning_w/_chat_-_(sodapoppin)_-_january_14,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2353239513_t1_vs_sodapoppin_duel_planning_w_chat_-_sodapoppin_-_january_14_2025.mp4
  link: https://www.youtube.com/watch?v=24xe9tc8_rA
  title: T1 vs Sodapoppin Duel Planning w/ Chat - (sodapoppin) - January 14, 2025
  uploaded_at: '2025-12-09 23:36:49'
data/sodapoppin/2025-01/2354081887_t1_vs_sodapoppin_duel_w/_chat_-_(sodapoppin)_-_january_15,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2354081887_t1_vs_sodapoppin_duel_w_chat_-_sodapoppin_-_january_15_2025.mp4
  link: https://www.youtube.com/watch?v=JknCVaJd6-k
  title: T1 vs Sodapoppin Duel w/ Chat - (sodapoppin) - January 15, 2025
  uploaded_at: '2025-12-09 23:38:44'
data/sodapoppin/2025-01/2355950535_casting_tyler1's_warcraft_iii_event_w/_chat_-_(sodapoppin)_-_january_17,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2355950535_casting_tyler1s_warcraft_iii_event_w_chat_-_sodapoppin_-_january_17_2025.mp4
  link: https://www.youtube.com/watch?v=hV-md_yC6Vw
  title: Casting Tyler1's Warcraft III Event w/ Chat - (sodapoppin) - January 17,
    2025
  uploaded_at: '2025-12-09 23:39:57'
data/sodapoppin/2025-01/2357816822_nelson_w/_chat_-_(sodapoppin)_-_january_19,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2357816822_nelson_w_chat_-_sodapoppin_-_january_19_2025.mp4
  link: https://www.youtube.com/watch?v=EMA37rV57rE
  title: Nelson w/ Chat - (sodapoppin) - January 19, 2025
  uploaded_at: '2025-12-09 23:40:03'
data/sodapoppin/2025-01/2358748593_alexbones_interview_w/_chat_-_(sodapoppin)_-_january_20,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2358748593_alexbones_interview_w_chat_-_sodapoppin_-_january_20_2025.mp4
  link: https://www.youtube.com/watch?v=t4_IC9WeHdo
  title: Alexbones Interview w/ Chat - (sodapoppin) - January 20, 2025
  uploaded_at: '2025-12-09 23:40:12'
data/sodapoppin/2025-01/2358748593_nelson_w/_chat_-_(sodapoppin)_-_january_20,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2358748593_nelson_w_chat_-_sodapoppin_-_january_20_2025.mp4
  link: https://www.youtube.com/watch?v=20SWsGe9n5s
  title: Nelson w/ Chat - (sodapoppin) - January 20, 2025
  uploaded_at: '2025-12-09 23:40:18'
data/sodapoppin/2025-01/2360544855_hide_and_seek_w/_chat_-_(sodapoppin)_-_january_22,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2360544855_hide_and_seek_w_chat_-_sodapoppin_-_january_22_2025.mp4
  link: https://www.youtube.com/watch?v=2crEypbJvGY
  title: Hide and Seek w/ Chat - (sodapoppin) - January 22, 2025
  uploaded_at: '2025-12-09 23:42:44'
data/sodapoppin/2025-01/2361397145_nelson_w/_chat_-_(sodapoppin)_-_january_23,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2361397145_nelson_w_chat_-_sodapoppin_-_january_23_2025.mp4
  link: https://www.youtube.com/watch?v=MrNwZTDNW0Y
  title: Nelson w/ Chat - (sodapoppin) - January 23, 2025
  uploaded_at: '2025-12-09 23:42:51'
data/sodapoppin/2025-01/2362517320_onlyfangs_irl_guild_meeting_w/_chat_-_(sodapoppin)_-_january_24,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2362517320_onlyfangs_irl_guild_meeting_w_chat_-_sodapoppin_-_january_24_2025.mp4
  link: https://www.youtube.com/watch?v=9Qc3E2s6gY0
  title: OnlyFangs IRL Guild Meeting w/ Chat - (sodapoppin) - January 24, 2025
  uploaded_at: '2025-12-09 23:44:05'
data/sodapoppin/2025-01/2363327420_nelson_w/_chat_-_(sodapoppin)_-_january_25,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2363327420_nelson_w_chat_-_sodapoppin_-_january_25_2025.mp4
  link: https://www.youtube.com/watch?v=0ZcyXb-Je3c
  title: Nelson w/ Chat - (sodapoppin) - January 25, 2025
  uploaded_at: '2025-12-09 23:44:13'
data/sodapoppin/2025-01/2364353892_nelson_w/_chat_-_(sodapoppin)_-_january_26,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2364353892_nelson_w_chat_-_sodapoppin_-_january_26_2025.mp4
  link: https://www.youtube.com/watch?v=AO-c4_DDmds
  title: Nelson w/ Chat - (sodapoppin) - January 26, 2025
  uploaded_at: '2025-12-09 23:54:36'
data/sodapoppin/2025-01/2364353892_warcraft_iii_custom_maps_w/_chat_-_(sodapoppin)_-_january_26,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2364353892_warcraft_iii_custom_maps_w_chat_-_sodapoppin_-_january_26_2025.mp4
  link: https://www.youtube.com/watch?v=_LrPeC9YPX8
  title: Warcraft III Custom Maps w/ Chat - (sodapoppin) - January 26, 2025
  uploaded_at: '2025-12-09 23:54:28'
data/sodapoppin/2025-01/2365214813_nelson_w/_chat_-_(sodapoppin)_-_january_27,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2365214813_nelson_w_chat_-_sodapoppin_-_january_27_2025.mp4
  link: https://www.youtube.com/watch?v=7QA5XsMIZSs
  title: Nelson w/ Chat - (sodapoppin) - January 27, 2025
  uploaded_at: '2025-12-09 23:54:40'
data/sodapoppin/2025-01/2366950968_nelson_w/_chat_-_(sodapoppin)_-_january_29,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2366950968_nelson_w_chat_-_sodapoppin_-_january_29_2025.mp4
  link: https://www.youtube.com/watch?v=6x-H6wJ29_o
  title: Nelson w/ Chat - (sodapoppin) - January 29, 2025
  uploaded_at: '2025-12-09 23:54:47'
data/sodapoppin/2025-01/2367853227_nelson_w/_chat_-_(sodapoppin)_-_january_30,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-01/2367853227_nelson_w_chat_-_sodapoppin_-_january_30_2025.mp4
  link: https://www.youtube.com/watch?v=gXe1TrGKfS4
  title: Nelson w/ Chat - (sodapoppin) - January 30, 2025
  uploaded_at: '2025-12-09 23:54:51'
data/sodapoppin/2025-02/2369520525_onlyfangs_molten_core_raid_w/_chat_-_(sodapoppin)_-_february_1,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2369520525_onlyfangs_molten_core_raid_w_chat_-_sodapoppin_-_february_1_2025.mp4
  link: https://www.youtube.com/watch?v=rhguiK6A0zw
  title: OnlyFangs Molten Core Raid w/ Chat - (sodapoppin) - February 1, 2025
  uploaded_at: '2025-12-10 22:21:47'
data/sodapoppin/2025-02/2374066827_kingdom_come:_deliverance_ii_#ad_w/_chat_-_(sodapoppin)_-_february_6,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2374066827_kingdom_come_deliverance_ii_ad_w_chat_-_sodapoppin_-_february_6_2025.mp4
  link: https://www.youtube.com/watch?v=Z3TkGULwVP4
  title: 'Kingdom Come: Deliverance II #ad w/ Chat - (sodapoppin) - February 6, 2025'
  uploaded_at: '2025-12-10 22:22:24'
data/sodapoppin/2025-02/2374953042_onlyfangs_molten_core_raid_(reaction)_w/_chat_-_(sodapoppin)_-_february_7,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2374953042_onlyfangs_molten_core_raid_reaction_w_chat_-_sodapoppin_-_february_7_2025.mp4
  link: https://www.youtube.com/watch?v=T9UI9QiKBhg
  title: OnlyFangs Molten Core Raid (Reaction) w/ Chat - (sodapoppin) - February 7,
    2025
  uploaded_at: '2025-12-10 22:25:00'
data/sodapoppin/2025-02/2374953042_onlyfangs_molten_core_raid_(reaction)_w/_chat_-_(sodapoppin)_-_february_7,_2025_muted:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2374953042_onlyfangs_molten_core_raid_reaction_w_chat_-_sodapoppin_-_february_7_2025_muted.mp4
  link: https://www.youtube.com/watch?v=NrAM611fNCs
  title: OnlyFangs Molten Core Raid (Reaction) w/ Chat - (sodapoppin) - February 7,
    2025
  uploaded_at: '2025-12-13 15:46:20'
data/sodapoppin/2025-02/2375792144_onlyfangs_molten_core_raid_w/_chat_-_(sodapoppin)_-_february_8,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2375792144_onlyfangs_molten_core_raid_w_chat_-_sodapoppin_-_february_8_2025.mp4
  link: https://www.youtube.com/watch?v=5krzieBJH1w
  title: OnlyFangs Molten Core Raid w/ Chat - (sodapoppin) - February 8, 2025
  uploaded_at: '2025-12-10 22:28:55'
data/sodapoppin/2025-02/2377573386_onlyfangs_molten_core_raid_(reaction)_w/_chat_-_(sodapoppin)_-_february_10,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2377573386_onlyfangs_molten_core_raid_reaction_w_chat_-_sodapoppin_-_february_10_2025.mp4
  link: https://www.youtube.com/watch?v=Qo0WKkGkNB4
  title: OnlyFangs Molten Core Raid (Reaction) w/ Chat - (sodapoppin) - February 10,
    2025
  uploaded_at: '2025-12-10 22:31:40'
data/sodapoppin/2025-02/2379488038_onlyfangs_molten_core_raid_w/_chat_-_(sodapoppin)_-_february_12,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2379488038_onlyfangs_molten_core_raid_w_chat_-_sodapoppin_-_february_12_2025.mp4
  link: https://www.youtube.com/watch?v=d86Hu7euB7I
  title: OnlyFangs Molten Core Raid w/ Chat - (sodapoppin) - February 12, 2025
  uploaded_at: '2025-12-10 22:33:39'
data/sodapoppin/2025-02/2387433399_onlyfangs_molten_core_raid_(reaction)_w/_chat_-_(sodapoppin)_-_february_21,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2387433399_onlyfangs_molten_core_raid_reaction_w_chat_-_sodapoppin_-_february_21_2025.mp4
  link: https://www.youtube.com/watch?v=DkfEYBkZbjs
  title: OnlyFangs Molten Core Raid (Reaction) w/ Chat - (sodapoppin) - February 21,
    2025
  uploaded_at: '2025-12-10 22:34:31'
data/sodapoppin/2025-02/2388277253_onlyfangs_molten_core_raid_(20)_w/_chat_-_(sodapoppin)_-_february_22,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2388277253_onlyfangs_molten_core_raid_20_w_chat_-_sodapoppin_-_february_22_2025.mp4
  link: https://www.youtube.com/watch?v=q_3Sr2b_1yo
  title: OnlyFangs Molten Core Raid (20) w/ Chat - (sodapoppin) - February 22, 2025
  uploaded_at: '2025-12-10 22:36:04'
data/sodapoppin/2025-02/2391777300_warcraft_iii_w/_chat_-_(sodapoppin)_-_february_26,_2025:
  file: /mnt/twitchvods/data_rendered/data/sodapoppin/2025-02/2391777300_warcraft_iii_w_chat_-_sodapoppin_-_february_26_2025.mp4
  link: https://www.youtube.com/watch?v=mxf5s9HIXb0
  title: Warcraft III w/ Chat - (sodapoppin) - February 26, 2025
  uploaded_at: '2025-12-10 22:37:15'
