
# yt_creds: 'sevadus_creds.json'
# yt_secrets: 'sevadus_secrets.json'

yt_template: 'sevadus_template.txt'

tags:
  - 'sevadus'
  - 'twitch'
  - 'vod'
  - 'streamer'
  - 'matt zagursky'
  - 'matt'
  - 'sev'
  - 'sevadusgaminglive'
  - 'games'
  - 'live'
  - 'live stream'
  - 'variety'
  - 'n3rdfusion'
  - 'nova'
  - 'otters'

