data/sodapoppin/2025-11/2626153687_bbb_w/_chat_-_(sodapoppin)_-_november_23,_2025:
  file: /home/patrick/Work/data_rendered/data/sodapoppin/2025-11/2626153687_bbb_w_chat_-_sodapoppin_-_november_23_2025.mp4
  rendered_at: '2025-11-24 20:56:38'
  test: this is a test
  title: BBB w/ Chat - (sodapoppin) - November 23, 2025
data/sodapoppin/2025-11/2626153687_test_03:
  rendered_at: '2025-11-24 21:02:11'
