

- video: sodapoppin/2020-11/807589404
  title: "The Pathless Full Playthrough (sodapoppin) - Nov 18, 2020"
  t_start: "04:32:01,04:36:45"
  t_end: "04:33:03,09:40:14"

# ===========================================
# ===========================================

- video: sodapoppin/2020-12/837193327
  title: "What is Moonmoon Doing? - (sodapoppin) - Dec 14, 2020"
  t_start: "08:18:47"
  t_end: "08:21:07"

- video: sodapoppin/2020-12/837193327
  title: "Live Stream Fails POGGERS - (sodapoppin) - Dec 14, 2020"
  t_start: "08:23:43"
  t_end: "08:28:58"

- video: sodapoppin/2020-12/837193327
  title: "What is 4Conner Doing? - (sodapoppin) - Dec 14, 2020"
  t_start: "08:36:20"
  t_end: "08:44:11"

- video: sodapoppin/2020-12/838421334
  title: "Soda Reacts to Random Videos - (sodapoppin) - Dec 15, 2020"
  t_start: "00:11:23,00:26:12"
  t_end: "00:25:27,02:02:29"

- video: sodapoppin/2020-12/838421334
  title: "Soda on Moonmoon's Bloons Defense Gameplay - (sodapoppin) - Dec 15, 2020"
  t_start: "06:50:24"
  t_end: "06:57:17"

- video: sodapoppin/2020-12/839568708
  title: "Spellbreak with Vigors #ad - (sodapoppin) - Dec 16, 2020"
  t_start: "03:16:38"
  t_end: "08:39:21"

- video: sodapoppin/2020-12/840766048
  title: "Chance Reacts to Soda You're So Music Video - (sodapoppin) - Dec 17, 2020"
  t_start: "00:07:54"
  t_end: "00:11:55"

- video: sodapoppin/2020-12/840766048
  title: "Chance Reacts to Shadowlands Arena Balance - (sodapoppin) - Dec 17, 2020"
  t_start: "00:13:05"
  t_end: "00:14:45"

- video: sodapoppin/2020-12/840766048
  title: "Chance Plays Closed Alpha Back 4 Blood - (sodapoppin) - Dec 17, 2020"
  t_start: "04:11:48"
  t_end: "09:21:37"

# ===========================================
# ===========================================

- video: sodapoppin/2020-12/841916008
  title: "Merch Store and Chance Remembers How to Write (sodapoppin) - Dec 18, 2020"
  t_start: "01:55:35"
  t_end: "02:05:05"

- video: sodapoppin/2020-12/841916008
  title: "Friday Dungeons & Dragons (flamewrath sodapoppin) - Dec 18, 2020"
  t_start: "02:05:23"
  t_end: "05:24:33"

- video: sodapoppin/2020-12/841916008
  title: "Back 4 Blood Closed Alpha with Dunkey, Leah and Vigors - (sodapoppin) - Dec 18, 2020"
  t_start: "05:50:23"
  t_end: "09:11:59"

# ===========================================
# ===========================================

- video: sodapoppin/2020-12/844322536
  title: "Chance's Christmas Shopping - (sodapoppin) - Dec 20, 2020"
  t_start: "00:09:17"
  t_end: "00:47:38"

- video: sodapoppin/2020-12/844322536
  title: "Chance Does Pushups - (sodapoppin) - Dec 20, 2020"
  t_start: "00:49:57"
  t_end: "01:04:58"

- video: sodapoppin/2020-12/844322536
  title: "Watching CashApp OTK Race to World First Highlights - (sodapoppin) - Dec 20, 2020"
  t_start: "02:45:56,03:02:53,03:22:24,05:45:35,05:56:16,05:59:33"
  t_end: "02:49:08,03:06:30,03:50:16,05:55:07,05:58:32,06:03:27"

- video: sodapoppin/2020-12/845278126
  title: "Chance Guesses Girls Ages - (sodapoppin) - Dec 21, 2020"
  t_start: "00:15:51"
  t_end: "00:32:23"

- video: sodapoppin/2020-12/845278126
  title: "Chance Guesses Girls Ages - (sodapoppin) - Dec 21, 2020"
  t_start: "00:15:51"
  t_end: "00:32:38"

- video: sodapoppin/2020-12/845278126
  title: "Chance Plays Crumble Platformer - (sodapoppin) - Dec 21, 2020"
  t_start: "00:35:17"
  t_end: "01:23:39"

- video: sodapoppin/2020-12/845278126
  title: "Chance Plays Morbid: The Seven Acolytes - (sodapoppin) - Dec 21, 2020"
  t_start: "01:27:56,01:35:29"
  t_end: "01:29:13,03:32:20"

- video: sodapoppin/2020-12/845278126
  title: "Chance Reacts to BotezLive Stream - (sodapoppin) - Dec 21, 2020"
  t_start: "03:41:18"
  t_end: "03:45:04"

- video: sodapoppin/2020-12/845278126
  title: "Chance Plays Tanuki Sunset (part 1)  - (sodapoppin) - Dec 21, 2020"
  t_start: "03:45:18"
  t_end: "04:58:21"

# ===========================================
# ===========================================

- video: sodapoppin/2020-12/853068127
  title: "WoW Peggle Gameplay (part 1) - (sodapoppin) - Dec 28, 2020"
  t_start: "07:35:35,07:38:28,08:00:56,08:36:51,10:34:21"
  t_end: "07:37:10,07:43:11,08:09:00,08:37:16,10:36:25"

- video: sodapoppin/2020-12/854335432
  title: "WoW Peggle Gameplay (part 2) - (sodapoppin) - Dec 29, 2020"
  t_start: "04:21:27,04:36:21,05:32:36,06:15:38"
  t_end: "04:23:17,04:38:46,05:34:05,06:17:21"


# ===========================================
# ===========================================

- video: austinshow/2020-12/855622774
  title: "LOVE or HOST Featuring Sodapoppin & Mommapoppin - Dec 30, 2020"
  t_start: "00:34:35"
  t_end: "05:24:27"

# ===========================================
# ===========================================

- video: sodapoppin/2020-12/856866672
  title: "Chance Plays Tanuki Sunset (part 2) - (sodapoppin) - Dec 31, 2020"
  t_start: "00:27:04"
  t_end: "01:21:00"

- video: sodapoppin/2020-12/856866672
  title: "Hanako Japanese Horror Game - (sodapoppin) - Dec 31, 2020"
  t_start: "01:35:38"
  t_end: "02:07:49"

- video: sodapoppin/2020-12/856866672
  title: "Chance Plays THE CORRIDOR - (sodapoppin) - Dec 31, 2020"
  t_start: "02:09:28"
  t_end: "02:38:16"

- video: sodapoppin/2020-12/856866672
  title: "Chance Plays The Dawn - (sodapoppin) - Dec 31, 2020"
  t_start: "02:49:30"
  t_end: "03:29:37"

- video: sodapoppin/2020-12/856866672
  title: "Alba: A Wildlife Adventure - (sodapoppin) - Dec 31, 2020"
  t_start: "03:35:36"
  t_end: "04:58:12"

- video: sodapoppin/2020-12/856866672
  title: "Pillow Simulator - (sodapoppin) - Dec 31, 2020"
  t_start: "05:03:19"
  t_end: "05:28:16"

- video: sodapoppin/2020-12/856866672
  title: "2021 New Year Recap of 2020 - (sodapoppin) - Dec 31, 2020"
  t_start: "05:36:29,06:18:20,07:17:30"
  t_end: "05:55:13,06:26:27,07:22:20"

- video: sodapoppin/2020-12/856866672
  title: "Wanba Warriors - (sodapoppin) - Dec 31, 2020"
  t_start: "05:55:13"
  t_end: "06:08:00"

- video: sodapoppin/2020-12/856866672
  title: "Wanba Warriors - (sodapoppin) - Dec 31, 2020"
  t_start: "05:55:13"
  t_end: "06:08:00"

- video: sodapoppin/2020-12/856866672
  title: "Sayonara Wild Hearts - (sodapoppin) - Dec 31, 2020"
  t_start: "06:27:12"
  t_end: "06:37:53"

- video: sodapoppin/2020-12/856866672
  title: "Shirt Competition - (sodapoppin) - Jan 1, 2021"
  t_start: "06:38:00"
  t_end: "07:54:16"











