data/sodapoppin/2025-01/2341488283_onlyfangs_hardcore_day_3.5_(subathon)_w/_chat_-_(sodapoppin)_-_january_1,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2341488283_onlyfangs_hardcore_day_35_subathon_w_chat_-_sodapoppin_-_january_1_2025.mp4
  link: https://www.youtube.com/watch?v=8_eBIuxfhQI
  title: OnlyFangs Hardcore Day 3.5 (subathon) w/ Chat - (sodapoppin) - January 1,
    2025
data/sodapoppin/2025-01/2341488283_onlyfangs_hardcore_day_3_(subathon)_w/_chat_-_(sodapoppin)_-_january_1,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2341488283_onlyfangs_hardcore_day_3_subathon_w_chat_-_sodapoppin_-_january_1_2025.mp4
  link: https://www.youtube.com/watch?v=uv3W7ohHvDE
  title: OnlyFangs Hardcore Day 3 (subathon) w/ Chat - (sodapoppin) - January 1, 2025
data/sodapoppin/2025-01/2341488283_onlyfangs_hardcore_day_4.5_(subathon)_w/_chat_-_(sodapoppin)_-_january_1,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2341488283_onlyfangs_hardcore_day_45_subathon_w_chat_-_sodapoppin_-_january_1_2025.mp4
  link: https://www.youtube.com/watch?v=BQXchNvGzvU
  title: OnlyFangs Hardcore Day 4.5 (subathon) w/ Chat - (sodapoppin) - January 1,
    2025
data/sodapoppin/2025-01/2341488283_onlyfangs_hardcore_day_4_(subathon)_w/_chat_-_(sodapoppin)_-_january_1,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2341488283_onlyfangs_hardcore_day_4_subathon_w_chat_-_sodapoppin_-_january_1_2025.mp4
  link: https://www.youtube.com/watch?v=69TGGdVv8OU
  title: OnlyFangs Hardcore Day 4 (subathon) w/ Chat - (sodapoppin) - January 1, 2025
data/sodapoppin/2025-01/2341488283_suprise_w/_chat_-_(sodapoppin)_-_january_1,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2341488283_suprise_w_chat_-_sodapoppin_-_january_1_2025.mp4
  link: https://www.youtube.com/watch?v=le3UDJoY4iQ
  title: Suprise w/ Chat - (sodapoppin) - January 1, 2025
data/sodapoppin/2025-01/2343182092_cooking_w/_chat_-_(sodapoppin)_-_january_3,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2343182092_cooking_w_chat_-_sodapoppin_-_january_3_2025.mp4
  link: https://www.youtube.com/watch?v=D83CMQpjnIs
  title: Cooking w/ Chat - (sodapoppin) - January 3, 2025
data/sodapoppin/2025-01/2343182092_onlyfangs_hardcore_day_5.5_(subathon)_w/_chat_-_(sodapoppin)_-_january_3,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2343182092_onlyfangs_hardcore_day_55_subathon_w_chat_-_sodapoppin_-_january_3_2025.mp4
  link: https://www.youtube.com/watch?v=w09j2DFsG9o
  title: OnlyFangs Hardcore Day 5.5 (subathon) w/ Chat - (sodapoppin) - January 3,
    2025
data/sodapoppin/2025-01/2343182092_onlyfangs_hardcore_day_5_(subathon)_w/_chat_-_(sodapoppin)_-_january_3,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2343182092_onlyfangs_hardcore_day_5_subathon_w_chat_-_sodapoppin_-_january_3_2025.mp4
  link: https://www.youtube.com/watch?v=dqTH2hkodGQ
  title: OnlyFangs Hardcore Day 5 (subathon) w/ Chat - (sodapoppin) - January 3, 2025
data/sodapoppin/2025-01/2343182092_vei_does_chance's_makeup_w/_chat_-_(sodapoppin)_-_january_3,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2343182092_vei_does_chances_makeup_w_chat_-_sodapoppin_-_january_3_2025.mp4
  link: https://www.youtube.com/watch?v=vZTKqg27Z7Y
  title: Vei Does Chance's Makeup w/ Chat - (sodapoppin) - January 3, 2025
data/sodapoppin/2025-01/2344199105_onlyfangs_hardcore_day_6_(subathon)_w/_chat_-_(sodapoppin)_-_january_4,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2344199105_onlyfangs_hardcore_day_6_subathon_w_chat_-_sodapoppin_-_january_4_2025.mp4
  link: https://www.youtube.com/watch?v=NFD6XE5nhdQ
  title: OnlyFangs Hardcore Day 6 (subathon) w/ Chat - (sodapoppin) - January 4, 2025
data/sodapoppin/2025-01/2345138072_onlyfangs_hardcore_day_7.5_(subathon)_w/_chat_-_(sodapoppin)_-_january_5,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2345138072_onlyfangs_hardcore_day_75_subathon_w_chat_-_sodapoppin_-_january_5_2025.mp4
  link: https://www.youtube.com/watch?v=OpmcG1IkRJI
  title: OnlyFangs Hardcore Day 7.5 (subathon) w/ Chat - (sodapoppin) - January 5,
    2025
data/sodapoppin/2025-01/2345138072_onlyfangs_hardcore_day_7_(subathon)_w/_chat_-_(sodapoppin)_-_january_5,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2345138072_onlyfangs_hardcore_day_7_subathon_w_chat_-_sodapoppin_-_january_5_2025.mp4
  link: https://www.youtube.com/watch?v=lJFH-Eg3gyU
  title: OnlyFangs Hardcore Day 7 (subathon) w/ Chat - (sodapoppin) - January 5, 2025
data/sodapoppin/2025-01/2345138072_onlyfangs_hardcore_day_8.5_(subathon)__w/_chat_-_(sodapoppin)_-_january_5,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2345138072_onlyfangs_hardcore_day_85_subathon__w_chat_-_sodapoppin_-_january_5_2025.mp4
  link: https://www.youtube.com/watch?v=lctfY1DaLZw
  title: OnlyFangs Hardcore Day 8.5 (subathon)  w/ Chat - (sodapoppin) - January 5,
    2025
data/sodapoppin/2025-01/2345138072_onlyfangs_hardcore_day_8_w/_chat_-_(sodapoppin)_-_january_5,_2025:
  file: /mnt/twitchvods/twitch_vod_creator/../data_rendered/data/sodapoppin/2025-01/2345138072_onlyfangs_hardcore_day_8_w_chat_-_sodapoppin_-_january_5_2025.mp4
  link: https://www.youtube.com/watch?v=eyB_Luzczn4
  title: OnlyFangs Hardcore Day 8 w/ Chat - (sodapoppin) - January 5, 2025
