
# ===========================================
# https://www.twitch.tv/sodapoppin/videos?filter=all
# ===========================================



- video: data/sodapoppin/2025-01/2341488283
  title: "OnlyFangs Hardcore Day 3 (subathon) w/ Chat - (sodapoppin) - January 1, 2025"
  t_start: "00:00:01"
  t_end: "06:45:29"

- video: data/sodapoppin/2025-01/2341488283
  title: "OnlyFangs Hardcore Day 3.5 (subathon) w/ Chat - (sodapoppin) - January 1, 2025"
  t_start: "06:45:29"
  t_end: "13:34:15"

- video: data/sodapoppin/2025-01/2341488283
  title: "Suprise w/ Chat - (sodapoppin) - January 1, 2025"
  t_start: "08:57:10"
  t_end: "09:21:40"


- video: data/sodapoppin/2025-01/2341488283
  title: "OnlyFangs Hardcore Day 4 (subathon) w/ Chat - (sodapoppin) - January 1, 2025"
  t_start: "22:55:27"
  t_end: "28:43:18"

- video: data/sodapoppin/2025-01/2341488283
  title: "OnlyFangs Hardcore Day 4.5 (subathon) w/ Chat - (sodapoppin) - January 1, 2025"
  t_start: "28:43:18"
  t_end: "34:55:05"


- video: data/sodapoppin/2025-01/2343182092
  title: "OnlyFangs Hardcore Day 5 (subathon) w/ Chat - (sodapoppin) - January 3, 2025"
  t_start: "00:00:03,03:08:16"
  t_end: "02:03:29,07:39:12"

- video: data/sodapoppin/2025-01/2343182092
  title: "OnlyFangs Hardcore Day 5.5 (subathon) w/ Chat - (sodapoppin) - January 3, 2025"
  t_start: "07:39:12"
  t_end: "12:44:29"


- video: data/sodapoppin/2025-01/2343182092
  title: "Vei Does Chance's Makeup w/ Chat - (sodapoppin) - January 3, 2025"
  t_start: "03:08:16"
  t_end: "08:02:04"

- video: data/sodapoppin/2025-01/2343182092
  title: "Cooking w/ Chat - (sodapoppin) - January 3, 2025"
  t_start: "07:45:30"
  t_end: "08:02:04"


- video: data/sodapoppin/2025-01/2344199105
  title: "OnlyFangs Hardcore Day 6 (subathon) w/ Chat - (sodapoppin) - January 4, 2025"
  t_start: "00:00:00"
  t_end: "09:52:22"


- video: data/sodapoppin/2025-01/2345138072
  title: "OnlyFangs Hardcore Day 7 (subathon) w/ Chat - (sodapoppin) - January 5, 2025"
  t_start: "00:00:00"
  t_end: "06:13:30"

- video: data/sodapoppin/2025-01/2345138072
  title: "OnlyFangs Hardcore Day 7.5 (subathon) w/ Chat - (sodapoppin) - January 5, 2025"
  t_start: "06:13:30"
  t_end: "11:51:40"




- video: data/sodapoppin/2025-01/2345138072
  title: "OnlyFangs Hardcore Day 8 w/ Chat - (sodapoppin) - January 5, 2025"
  t_start: "21:51:34"
  t_end: "27:20:04"

- video: data/sodapoppin/2025-01/2345138072
  title: "OnlyFangs Hardcore Day 8.5 (subathon)  w/ Chat - (sodapoppin) - January 5, 2025"
  t_start: "27:20:04"
  t_end: "32:42:49"



# - video: data/mizkif/2025-01/2362500298
#   title: "OnlyFangs IRL Guild Meeting w/ Chat - (Mizkif) - January 24, 2025"
#   t_start: "00:22:07"
#   t_end: "03:30:52"





